### ISSUE TITLE
Problem with /interact link

### ISSUE THREAD

**Issue by papajohn** [data-8/jupyterhub-deploy#3]
From @cboettig 

"[I'm trying to] deliver material to students ... by using the link strategy used by the textbook.  This does sound very slick, but sadly I haven't had luck in getting this to work from GitHub.  My attempt here: https://github.com/boettiger-lab/espm-88b/tree/master/modules/climate (click either link in the readme).  What did I miss?"

My guess is that our `interact` links don't handle `https` or redirects correctly. @alvinwan @ryanlovett

**Comment by ryanlovett** [comment]
We allow files from data8.org:

https://github.com/dsten/DS8-Interact/blob/master/app/config.py#L36.
https://github.com/dsten/DS8-Interact/blob/master/app/__init__.py#L55

In chatting with @SamLau95, we thought connector instructors could upload to the gh-pages branch of their dsten/$connector_repo. The notebooks would then show up at data8.org as I understood it. Alternatively we could add some other whitelisting.

**Comment by cboettig** [comment]
Hi @ryanlovett @papajohn ,

Thanks for the help!  That sounds promising but no go for me; e.g. this link now gives me a 422 error instead of a 500 error: https://ds8.berkeley.edu/hub/interact/?http://data8.org/ecology-connector/climate/climate.ipynb

Error message is; `Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors.`

Sources are in the gh-pages branch.  not sure what I've messed up this time.

**Comment by SamLau95** [comment]
Ah, try
https://ds8.berkeley.edu/hub/interact?file=http://data8.org/ecology-connector/climate/climate.ipynb

**Comment by cboettig** [comment]
Silly me dropping the `file=` argument; thanks.  Feel free to close.

Some documentation on using this link structure along with notebooks on the gh-pages branch of a connector repo might be nice; maybe in https://github.com/dsten/connector-instructors

**Comment by ryanlovett** [comment]
Good idea, done!
